import type {
  ApprovalRecord,
  DepartmentModuleState,
  InventoryModuleState,
  ReceptionModuleState,
} from "./types";

export const MOCK_VIP_RECORD: DepartmentModuleState = {
  id: "vip-001",
  module: "vip",
  date: new Date().toISOString().slice(0, 10),
  status: "draft",
  rows: [
    {
      id: "vip-row-1",
      drinkName: "Water",
      openingStock: 30,
      newStock: 10,
      totalStock: 40,
      closingStock: 18,
      drinksSold: 0,
      price: 2,
      amount: 0,
      damages: 1,
      transfers: 2,
    },
    {
      id: "vip-row-2",
      drinkName: "Sparkling Juice",
      openingStock: 18,
      newStock: 6,
      totalStock: 24,
      closingStock: 8,
      drinksSold: 0,
      price: 4,
      amount: 0,
      damages: 0,
      transfers: 0,
    },
  ],
  transfersSection: 0,
  pos: 0,
  bossCollectedCash: 0,
  debtsExplanation: "nill",
  submittedBy: "VIP Master",
  warnings: [],
};

export const MOCK_BAR_RECORD: DepartmentModuleState = {
  id: "bar-001",
  module: "bar",
  date: new Date().toISOString().slice(0, 10),
  status: "draft",
  rows: [
    {
      id: "bar-row-1",
      drinkName: "Beer",
      openingStock: 45,
      newStock: 12,
      totalStock: 57,
      closingStock: 20,
      drinksSold: 0,
      price: 6,
      amount: 0,
      damages: 2,
      transfers: 1,
    },
    {
      id: "bar-row-2",
      drinkName: "Cider",
      openingStock: 16,
      newStock: 4,
      totalStock: 20,
      closingStock: 7,
      drinksSold: 0,
      price: 5,
      amount: 0,
      damages: 0,
      transfers: 0,
    },
  ],
  transfersSection: 0,
  pos: 0,
  bossCollectedCash: 0,
  debtsExplanation: "nill",
  submittedBy: "Bar Master",
  warnings: [],
};

export const MOCK_RECEPTION_RECORD: ReceptionModuleState = {
  id: "rec-001",
  module: "reception",
  date: new Date().toISOString().slice(0, 10),
  status: "draft",
  rows: [
    {
      id: "rec-row-1",
      customerName: "Jane Doe",
      sex: "Female",
      timeIn: "14:00",
      timeOut: "10:00",
      room: "A12",
      idNumber: "ID-48393",
      pos: 200,
      transfer: 0,
      cash: 300,
      duration: "1 day",
      roomRate: 500,
      amountPaid: 500,
      existing: false,
    },
    {
      id: "rec-row-2",
      customerName: "Mark Green",
      sex: "Male",
      timeIn: "16:00",
      timeOut: "11:00",
      room: "B08",
      idNumber: "ID-88811",
      pos: 150,
      transfer: 100,
      cash: 250,
      duration: "2 days",
      roomRate: 350,
      amountPaid: 500,
      existing: true,
    },
  ],
  submittedBy: "Receptionist",
  warnings: [],
};

export const MOCK_INVENTORY_RECORD: InventoryModuleState = {
  id: "inv-001",
  module: "inventory",
  date: new Date().toISOString().slice(0, 10),
  status: "draft",
  purchases: [
    {
      id: "inv-row-1",
      itemName: "Vodka Box",
      quantity: 3,
      unitPrice: 42,
      totalCost: 126,
      department: "Store",
    },
    {
      id: "inv-row-2",
      itemName: "Energy Drink Case",
      quantity: 5,
      unitPrice: 18,
      totalCost: 90,
      department: "Bar",
      inconsistency: "",
    },
  ],
  transfersToBar: 40,
  transfersToVip: 20,
  flaggedInconsistencies: [],
  submittedBy: "Admin",
};

export const MOCK_APPROVAL_RECORDS: ApprovalRecord[] = [
  {
    id: "app-001",
    date: new Date().toISOString().slice(0, 10),
    module: "vip",
    title: "VIP Daily Record",
    status: "submitted",
    debtStatus: "partial",
    cashAtHand: 1200,
    submittedBy: "VIP Master",
    notes: "Needs cash verification.",
  },
  {
    id: "app-002",
    date: new Date().toISOString().slice(0, 10),
    module: "bar",
    title: "Bar Daily Record",
    status: "reviewed",
    debtStatus: "none",
    cashAtHand: 900,
    submittedBy: "Bar Master",
    notes: "Balanced.",
  },
  {
    id: "app-003",
    date: new Date().toISOString().slice(0, 10),
    module: "reception",
    title: "Reception Lodging Record",
    status: "approved",
    debtStatus: "full",
    cashAtHand: 2400,
    submittedBy: "Receptionist",
    notes: "Ready for sign off.",
  },
];
